# Generated by Django 5.2 on 2025-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinopoisk_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('countries', models.JSONField(default=list)),
            ],
        ),
    ]
